export const fonts = {
    RubikBlack: "Rubik-Black",
    RubikBlackItalic: "Rubik-BlackItalic",
    RubikBold: "Rubik-Bold",
    RubikBoldItalic: "Rubik-BoldItalic",
    RubikExtraBold: "Rubik-ExtraBold",
    RubikExtraBoldItalic: "Rubik-ExtraBoldItalic",
    RubikItalic: "Rubik-Italic",
    RubikLight: "Rubik-Light",
    RubikLightItalic: "Rubik-LightItalic",
    RubikMedium: "Rubik-Medium",
    RubikMediumItalic: "Rubik-MediumItalic",
    RubikRegular: "Rubik-Regular",
    RubikSemiBold: "Rubik-SemiBold",
    RubikSemiBoldItalic: "Rubik-SemiBoldItalic",
};